"""Package the whole project into one archive and one readable text file.

    python tools/make_bundle.py            # everything, as a zip + one big file
    python tools/make_bundle.py --core     # only the numerics, as one file
    python tools/make_bundle.py --core-dir # only the numerics, as a folder

Produces, in the project root:

* ``robertson_code_bundle.zip`` -- every source file under its original path,
  so an unzip gives a working checkout::

      python run_all.py            # rebuild results/
      python -m pytest tests -q    # 148 tests

* ``robertson_all_code.md`` -- the same files inlined in one document, for
  reading or pasting, with a table of contents and per-file line counts.

* ``robertson_core/`` (``--core-dir``) -- the numerics as a real directory tree,
  with the reference solution alongside it so every module in it runs.

What is *not* shipped: ``results/`` is regenerated by ``run_all.py``, and the
3.2 MB of figures in particular would dwarf the code.  Four files under
``results/`` are shipped anyway because the test suite reads them:

* ``results/reference/{reference.npz,metadata.json,characterisation.json}`` --
  ``jacobian_check`` and ``newton_estimator`` load the reference solution to
  pick the states whose Jacobian they check.  Without it, 16 tests fail on a
  fresh checkout.
* ``results/summary.json`` -- one test asserts the Newton-tolerance threshold
  against the *measured* explicit-Euler stability bound stored here, instead of
  hard-coding a number.

Neither the archive nor the text file contains itself: both are written after
the file list is taken.
"""

from __future__ import annotations

import pathlib
import shutil
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[1]

# Output names, declared before the skip sets because the outputs must be
# skipped: without ``robertson_core`` here, generating the folder once makes the
# next archive contain a copy of it (53 files became 83 the first time).
ZIP_NAME = "robertson_code_bundle.zip"
TEXT_NAME = "robertson_all_code.md"
CORE_NAME = "robertson_core_code.md"
CORE_DIR_NAME = "robertson_core"

#: First line of the folder's README.  ``--core-dir`` refuses to replace a
#: directory that does not carry this marker, so pointing it at a real folder
#: by accident cannot delete anything.
CORE_DIR_MARKER = "# Robertson 问题：核心代码（文件夹版）"

SKIP_DIRS = {"build", "__pycache__", ".pytest_cache", ".git", "dist",
             ".mypy_cache", ".ipynb_checkpoints", CORE_DIR_NAME}
SKIP_FILES = {".DS_Store", ZIP_NAME, TEXT_NAME, CORE_NAME}
CODE_EXT = {".py", ".tex", ".yaml", ".yml", ".toml", ".cfg", ".txt", ".sh", ".json"}
DOC_EXT = {".md"}
BINARY_EXT = {".npz", ".pdf", ".png"}
LANG = {".py": "python", ".tex": "latex", ".yaml": "yaml", ".yml": "yaml",
        ".toml": "toml", ".cfg": "ini", ".txt": "text", ".sh": "bash",
        ".json": "json", ".md": "markdown"}

KEEP = {"results/reference/reference.npz",
        "results/reference/metadata.json",
        "results/reference/characterisation.json",
        "results/summary.json"}

#: ``--core``: only the numerics.  The model, the integrators (including the
#: Newton solver and the adaptive controller) and the analysis that measures
#: them.  Left out on purpose: ``run_all.py`` (orchestration), ``src/reporting``
#: (matplotlib and CSV writers), ``tests``, ``tools``, ``slides`` and the prose
#: docs -- together about three quarters of the line count.
CORE_DIRS = ("src/model", "src/integrators", "src/analysis")
CORE_FILES = ("src/grid.py", "src/__init__.py",
              "config/default.yaml", "requirements.txt")

#: Copied into ``robertson_core/`` as well.  Both analysis modules locate the
#: reference solution at ``<root>/results/reference/reference.npz``, where
#: ``<root>`` is two levels above ``src/analysis/`` -- so in the folder copy the
#: file has to sit at ``results/reference/`` like it does here.  136 KB, and
#: without it two of the ten modules cannot be called at all.
CORE_DIR_EXTRA = ("results/reference/reference.npz",
                  "results/reference/metadata.json",
                  "results/reference/characterisation.json")


def _is_project_copy(p: pathlib.Path) -> bool:
    """True for a directory that carries this project's own signature.

    The archive gets unzipped next to the tree it came from more often than one
    would like, and a nested copy doubles the file list.  Matching on the name
    is not enough: an extractor that finds the name taken writes
    ``<name> 2``, which is a different string and therefore invisible to a name
    test.  The signature does not move.
    """
    return ((p / "run_all.py").is_file()
            and (p / "src" / "model" / "robertson.py").is_file())


def _skip(rel: pathlib.Path) -> bool:
    """True for anything that must never enter a bundle."""
    if any(part in SKIP_DIRS for part in rel.parts[:-1]):
        return True
    top = rel.parts[0]
    if top == ROOT.name:
        return True
    return (ROOT / top).is_dir() and _is_project_copy(ROOT / top)


def collect() -> list[pathlib.Path]:
    """Every file that belongs in the bundle, in a stable order."""
    out = []
    for p in sorted(ROOT.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        if _skip(rel):
            continue
        if p.name in SKIP_FILES:
            continue
        if str(rel) in KEEP:
            out.append(p)
            continue
        if rel.parts[0] == "results":
            continue
        if p.suffix.lower() in CODE_EXT | DOC_EXT:
            out.append(p)
    return out


def collect_core() -> list[pathlib.Path]:
    """The numerics only: model, integrators, analysis, plus config."""
    out = []
    for p in sorted(ROOT.rglob("*")):
        if not p.is_file() or p.name in SKIP_FILES:
            continue
        rel = p.relative_to(ROOT)
        if _skip(rel):
            continue
        if str(rel) in CORE_FILES or str(rel).startswith(CORE_DIRS):
            out.append(p)
    return out


def is_text(p: pathlib.Path) -> bool:
    return p.suffix.lower() not in BINARY_EXT


CORE_HEADER = """# Robertson 问题：核心代码

只包含数值部分——问题定义、积分器（含 Newton 求解器与自适应控制器）、
以及度量它们的分析代码。共 **{n}** 个文件、**{nl}** 行。

按块统计的取舍（行数）：

| 块 | 行数 | 收不收 |
|---|---|---|
| `src/model` `src/integrators` `src/analysis` `src/grid.py` 数值本体 | 3433 | 收 |
| `config/default.yaml` `requirements.txt` | 166 | 收 |
| `src/reporting` 画图与出表（matplotlib / CSV） | 1460 | 不收 |
| `run_all.py` 阶段编排 | 594 | 不收 |
| `tests/` 148 个测试 | 1857 | 不收 |
| `tools/` 后处理脚本 | 851 | 不收 |
| `slides/` 幻灯片源码 | 1044 | 不收 |
| `appendix/` 与两个 README | 2025 | 不收 |

> 两点使用须知。**其一**，这里没有 `run_all.py` 和 `src/reporting`，所以是一条
> 库而不是一条流水线：可以 `from src.integrators import make` 直接用，
> 但不能 `python run_all.py`。
> **其二**，`jacobian_check.py` 与 `newton_estimator.py` 会读取
> `results/reference/reference.npz` 来挑 Jacobian 校验用的代表状态，
> 所以这两个模块要跑，得先生成参考解（`python run_all.py --stages reference`）。

---
"""


def build_core_dir() -> pathlib.Path:
    """Materialise ``robertson_core/``: the numerics as a real directory tree.

    The single-file listing is for reading and pasting; this is for opening in an
    editor and running.  Contents are ``collect_core()`` plus the reference
    solution the two analysis modules load, plus ``example.py``.

    Refuses to touch a directory that does not start with
    :data:`CORE_DIR_MARKER`, so a mistyped target cannot delete anything.
    """
    dest = ROOT / CORE_DIR_NAME
    if dest.exists():
        marker = dest / "README.md"
        head = marker.read_text(encoding="utf-8") if marker.exists() else ""
        if not head.startswith(CORE_DIR_MARKER):
            raise SystemExit(
                f"refusing to overwrite {dest}\n"
                f"  (no {CORE_DIR_NAME} README at the top of it).  Move it aside "
                f"or delete it yourself if that is really what you want.")
        shutil.rmtree(dest)

    files = collect_core()
    for f in files:
        _copy(f, dest / f.relative_to(ROOT))
    for rel in CORE_DIR_EXTRA:
        _copy(ROOT / rel, dest / rel)
    example = ROOT / "tools" / "core_example.py"
    if example.is_file():
        _copy(example, dest / "example.py")

    shipped = [f.relative_to(ROOT).as_posix() for f in files]
    shipped += list(CORE_DIR_EXTRA)
    if example.is_file():
        shipped.append("example.py")
    shipped.append("README.md")

    texty = [f for f in files if is_text(f)]
    nl = sum(len(f.read_text().splitlines()) for f in texty)
    (dest / "README.md").write_text(
        CORE_DIR_README.format(marker=CORE_DIR_MARKER, n=len(files), nl=nl,
                               nref=len(CORE_DIR_EXTRA), tree=_tree(shipped)),
        encoding="utf-8")
    return dest


def _copy(src: pathlib.Path, dest: pathlib.Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)


def _tree(rels: list[str]) -> str:
    """A plain-art directory tree for a list of relative POSIX paths."""
    root: dict = {}
    for r in rels:
        node = root
        for part in pathlib.PurePosixPath(r).parts:
            node = node.setdefault(part, {})
    lines: list[str] = []

    def walk(node: dict, prefix: str = "") -> None:
        # directories first, then files, each alphabetically
        for i, (name, child) in enumerate(
                sorted(node.items(), key=lambda kv: (not kv[1], kv[0]))):
            last = i == len(node) - 1
            lines.append(f"{prefix}{'└── ' if last else '├── '}{name}")
            if child:
                walk(child, prefix + ("    " if last else "│   "))

    walk(root)
    return "\n".join(lines)


CORE_DIR_README = """{marker}

只放数值部分：问题定义、积分器（含 Newton 求解器与自适应控制器），以及度量它们的
分析代码。**{n} 个源文件 / {nl} 行**，另附参考解（{nref} 个文件，136 KB）——
两个分析模块要读它来挑 Jacobian 校验点。

```
{tree}
```

## 怎么用

```python
import sys; sys.path.insert(0, "/path/to/robertson_core")
from src.model import robertson as R
from src.integrators import make

tr = make("implicit_euler", h=1.0e-2, newton_tol=1.0e-12).integrate(
    1.0e-2, t_end=1.0, y0=R.Y0)
print(tr.endpoint(), tr.stats.rhs_calls)
```

或者直接 `python example.py`：它把六件事跑一遍并打印实测值（守恒、阻尼 vs 预测子、
刚性对照、谱、Jacobian 逐列校验、停机容差换方法），不看表格也能确认这套代码活着。

依赖只有 `numpy`；`requirements.txt` 里的 SciPy 是 `src/analysis/reference.py`
造参考解用的，matplotlib 与 pytest 属于本文件夹之外的部分。

## 三件要说清的事

1. **这是库，不是流水线。** 没有 `run_all.py`（阶段编排），也没有
   `src/reporting`（matplotlib 画图与 CSV 出表），所以 `python run_all.py`
   在这里不存在。要完整流水线，用项目根目录的 `robertson_code_bundle.zip`。
2. **`results/` 里只有 `reference/` 三个文件**，其余（约 3.2 MB 的图、`raw/`、
   `tables/`）由 `run_all.py` 生成，没有收录。
3. **参考解的路径是算出来的，不是配的。** 两个分析模块用
   `Path(__file__).resolve().parents[2]` 定位 `results/reference/reference.npz`，
   所以别改动 `src/` 的层级，否则会 `FileNotFoundError`。

`example.py` 不是项目源码，是本文件夹自带的示例。
生成方式：在项目根目录执行 `python tools/make_bundle.py --core-dir`。
本文件夹是生成物，可以随时删掉重生成。
"""


def main(core: bool = False) -> None:
    files = collect_core() if core else collect()
    texty = [f for f in files if is_text(f)]
    n, nt = len(files), len(texty)
    nl = sum(len(f.read_text().splitlines()) for f in texty)
    print(f"{n} files ({nt} text, {n - nt} binary), {nl} lines")

    # ---- the archive ------------------------------------------------------
    if not core:
        zpath = ROOT / ZIP_NAME
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
            for f in files:
                z.write(f, pathlib.Path(ROOT.name) / f.relative_to(ROOT))
        print(f"zip  : {zpath.name}  ({zpath.stat().st_size / 1024:.1f} KB)")

    # ---- the single readable file -----------------------------------------
    if core:
        parts: list[str] = [CORE_HEADER.format(n=n, nl=nl)]
        parts.append("\n## 目录\n\n")
    else:
        parts = ["# Robertson 问题：全部源码（单文件合集）\n\n"]
        parts.append(
            f"项目共 **{n}** 个文件，其中 **{nt}** 个源码/配置文件的内容原样附在下面。\n\n"
            f"配套的压缩包 `{ZIP_NAME}` 保留原始目录结构，解压即可运行：\n\n"
            "```sh\npython run_all.py            # 重算 results/ 下的每一张表和每一张图\n"
            "python -m pytest tests -q    # 148 个测试（已验证：干净解压下 148 passed）\n```\n\n"
            "> `results/` 下的图片（约 3.2 MB）、`raw/` 与 `tables/` **没有**收录，它们全部由\n"
            "> `run_all.py` 重建。另附 4 个非源码文件，是为了让测试能在解压后立刻通过：\n"
            "> `results/reference/` 三个文件（两个分析模块要读参考解来挑 Jacobian 校验点）\n"
            "> 和 `results/summary.json`（有一条测试拿它里面的**实测**稳定界做断言，\n"
            "> 而不是硬编码一个数）。`slides/build/` 与各类缓存目录同样未收录。\n\n"
            "---\n\n## 目录\n\n"
        )
    for i, f in enumerate(files, 1):
        rel = f.relative_to(ROOT)
        if is_text(f):
            parts.append(f"{i:>3}. `{rel}` — {len(f.read_text().splitlines())} 行\n")
        else:
            parts.append(f"{i:>3}. `{rel}` — 二进制，"
                         f"{f.stat().st_size / 1024:.1f} KB（见压缩包）\n")
    parts.append("\n---\n")

    for i, f in enumerate(files, 1):
        rel = f.relative_to(ROOT)
        parts.append(f"\n## {i}. `{rel}`\n\n")
        if not is_text(f):
            parts.append(f"*二进制文件（{f.stat().st_size / 1024:.1f} KB），"
                         f"内容见压缩包 `{ZIP_NAME}`。*\n")
            continue
        body = f.read_text()
        if not body.endswith("\n"):
            body += "\n"
        fence = "`" * 4 if "```" in body else "`" * 3
        parts.append(f"{fence}{LANG.get(f.suffix.lower(), 'text')}\n{body}{fence}\n")
    parts.append(f"\n---\n\n*文件结束。共 {n} 个文件，{nt} 个已内联。*\n")

    mpath = ROOT / (CORE_NAME if core else TEXT_NAME)
    mpath.write_text("".join(parts))
    print(f"text : {mpath.name}  ({mpath.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--core", action="store_true",
                    help="only the numerics, as one readable file (no zip)")
    ap.add_argument("--core-dir", action="store_true",
                    help="only the numerics, as a runnable directory tree")
    a = ap.parse_args()
    if a.core_dir:
        d = build_core_dir()
        print(f"dir  : {d.relative_to(ROOT)}/  "
              f"({sum(1 for _ in d.rglob('*') if _.is_file())} files, "
              f"{sum(f.stat().st_size for f in d.rglob('*') if f.is_file()) / 1024:.0f} KB)")
    else:
        main(core=a.core)
